// english-vocab.js
// -----------------------------------------------------------------------
// The official reading and writing vocabulary lists from USCIS Form
// M-1122, "Preparing for the Naturalization Test: A Pocket Study Guide"
// (rev. 07/2024). USCIS states this content "is considered public
// information and may be distributed or copied without alteration."
// -----------------------------------------------------------------------

const READING_VOCAB = [
  { word: "Abraham Lincoln", category: "People" },
  { word: "George Washington", category: "People" },
  { word: "American flag", category: "Civics" },
  { word: "Bill of Rights", category: "Civics" },
  { word: "capital", category: "Civics" },
  { word: "citizen", category: "Civics" },
  { word: "city", category: "Civics" },
  { word: "Congress", category: "Civics" },
  { word: "country", category: "Civics" },
  { word: "Father of Our Country", category: "Civics" },
  { word: "government", category: "Civics" },
  { word: "President", category: "Civics" },
  { word: "right", category: "Civics" },
  { word: "Senators", category: "Civics" },
  { word: "state/states", category: "Civics" },
  { word: "White House", category: "Civics" },
  { word: "America", category: "Places" },
  { word: "United States", category: "Places" },
  { word: "U.S.", category: "Places" },
  { word: "Presidents\u2019 Day", category: "Holidays" },
  { word: "Memorial Day", category: "Holidays" },
  { word: "Flag Day", category: "Holidays" },
  { word: "Independence Day", category: "Holidays" },
  { word: "Labor Day", category: "Holidays" },
  { word: "Columbus Day", category: "Holidays" },
  { word: "Thanksgiving", category: "Holidays" },
  { word: "How", category: "Question Words" },
  { word: "What", category: "Question Words" },
  { word: "When", category: "Question Words" },
  { word: "Where", category: "Question Words" },
  { word: "Who", category: "Question Words" },
  { word: "Why", category: "Question Words" },
  { word: "can", category: "Verbs" },
  { word: "come", category: "Verbs" },
  { word: "do/does", category: "Verbs" },
  { word: "elects", category: "Verbs" },
  { word: "have/has", category: "Verbs" },
  { word: "is/are/was/be", category: "Verbs" },
  { word: "lives/lived", category: "Verbs" },
  { word: "meet", category: "Verbs" },
  { word: "name", category: "Verbs" },
  { word: "pay", category: "Verbs" },
  { word: "vote", category: "Verbs" },
  { word: "want", category: "Verbs" },
  { word: "a", category: "Other (Function)" },
  { word: "for", category: "Other (Function)" },
  { word: "here", category: "Other (Function)" },
  { word: "in", category: "Other (Function)" },
  { word: "of", category: "Other (Function)" },
  { word: "on", category: "Other (Function)" },
  { word: "the", category: "Other (Function)" },
  { word: "to", category: "Other (Function)" },
  { word: "we", category: "Other (Function)" },
  { word: "colors", category: "Other (Content)" },
  { word: "dollar bill", category: "Other (Content)" },
  { word: "first", category: "Other (Content)" },
  { word: "largest", category: "Other (Content)" },
  { word: "many", category: "Other (Content)" },
  { word: "most", category: "Other (Content)" },
  { word: "north", category: "Other (Content)" },
  { word: "one", category: "Other (Content)" },
  { word: "people", category: "Other (Content)" },
  { word: "second", category: "Other (Content)" },
  { word: "south", category: "Other (Content)" },
];

const WRITING_VOCAB = [
  { word: "Adams", category: "People" },
  { word: "Lincoln", category: "People" },
  { word: "Washington", category: "People" },
  { word: "American Indians", category: "Civics" },
  { word: "capital", category: "Civics" },
  { word: "citizens", category: "Civics" },
  { word: "Civil War", category: "Civics" },
  { word: "Congress", category: "Civics" },
  { word: "Father of Our Country", category: "Civics" },
  { word: "flag", category: "Civics" },
  { word: "free", category: "Civics" },
  { word: "freedom of speech", category: "Civics" },
  { word: "President", category: "Civics" },
  { word: "right", category: "Civics" },
  { word: "Senators", category: "Civics" },
  { word: "state/states", category: "Civics" },
  { word: "White House", category: "Civics" },
  { word: "Alaska", category: "Places" },
  { word: "California", category: "Places" },
  { word: "Canada", category: "Places" },
  { word: "Delaware", category: "Places" },
  { word: "Mexico", category: "Places" },
  { word: "New York City", category: "Places" },
  { word: "United States", category: "Places" },
  { word: "Washington", category: "Places" },
  { word: "Washington, D.C.", category: "Places" },
  { word: "February", category: "Months" },
  { word: "May", category: "Months" },
  { word: "June", category: "Months" },
  { word: "July", category: "Months" },
  { word: "September", category: "Months" },
  { word: "October", category: "Months" },
  { word: "November", category: "Months" },
  { word: "Presidents\u2019 Day", category: "Holidays" },
  { word: "Memorial Day", category: "Holidays" },
  { word: "Flag Day", category: "Holidays" },
  { word: "Independence Day", category: "Holidays" },
  { word: "Labor Day", category: "Holidays" },
  { word: "Columbus Day", category: "Holidays" },
  { word: "Thanksgiving", category: "Holidays" },
  { word: "can", category: "Verbs" },
  { word: "come", category: "Verbs" },
  { word: "elect", category: "Verbs" },
  { word: "have/has", category: "Verbs" },
  { word: "is/was/be", category: "Verbs" },
  { word: "lives/lived", category: "Verbs" },
  { word: "meets", category: "Verbs" },
  { word: "pay", category: "Verbs" },
  { word: "vote", category: "Verbs" },
  { word: "want", category: "Verbs" },
  { word: "and", category: "Other (Function)" },
  { word: "during", category: "Other (Function)" },
  { word: "for", category: "Other (Function)" },
  { word: "here", category: "Other (Function)" },
  { word: "in", category: "Other (Function)" },
  { word: "of", category: "Other (Function)" },
  { word: "on", category: "Other (Function)" },
  { word: "the", category: "Other (Function)" },
  { word: "to", category: "Other (Function)" },
  { word: "we", category: "Other (Function)" },
  { word: "blue", category: "Other (Content)" },
  { word: "dollar bill", category: "Other (Content)" },
  { word: "fifty/50", category: "Other (Content)" },
  { word: "first", category: "Other (Content)" },
  { word: "largest", category: "Other (Content)" },
  { word: "most", category: "Other (Content)" },
  { word: "north", category: "Other (Content)" },
  { word: "one", category: "Other (Content)" },
  { word: "one hundred/100", category: "Other (Content)" },
  { word: "people", category: "Other (Content)" },
  { word: "red", category: "Other (Content)" },
  { word: "second", category: "Other (Content)" },
  { word: "south", category: "Other (Content)" },
  { word: "taxes", category: "Other (Content)" },
  { word: "white", category: "Other (Content)" },
];
